hyde:
  sidebar:
    sticky: true  # Content to the bottom of the sidebar
  theme: ''       # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false  # Reverse layout
  fonts: 'google' # google or local

pagination:
  max: 5
  path: 'page'
libs:
  highlight:
    version: '11.4.0'
    style: 'monokai-sublime'
